Attribute VB_Name = "Module1"
Public iHighv As Integer
Public iLowV As Integer
Public iMathcase   As Integer
Public cSymbol(5) As String
Public iAnswer As Integer
Public iFoe As Integer
Public iFoeold As Integer
Public iWincnt As Integer
Public iGamecnt As Integer
